name: Build Electron ARM64

on:
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
        working-directory: ./app
      - run: npx electron-forge make --platform linux --arch arm64
        working-directory: ./app
      - name: Upload .deb file
        uses: actions/upload-artifact@v4
        with:
          name: electron-deb
          path: ./app/out/make/deb/
